### ISSUE TITLE
Feedback section

### ISSUE THREAD

**Issue by Auel** [aidaroff/mypass.co#1]
Feedback section to be added,
text:
Команда mypass будет рада Вашим замечаниям и пожеланиям. Форма заявки

**Comment by aidaroff** [comment]
want to add feedback zone to footer? there can be our email or link to a form. We don't have much for the footer anyways. Since navigation is sticky (it scrolls down as you scroll down the page) we don't need any links. We don't have address or other contact information (phone number is on navigation)

**Comment by aidaroff** [comment]
I'm going to go ahead and try. After I close this issue check it out, and reopen if you don't like it.

**Comment by aidaroff** [comment]
we can also add subscribe button, a link to Google forms to gather people's emails? what do you think?

**Comment by Auel** [comment]
nice idea, however don't u think that it will look too unsistematically. too many fields to fill in. let's try and see, then will talk in details
